// Generated by scripts/sync-brand-logos.mjs.
export type ComponentLogo = { slug: string; title: string; color: string };
export const componentLogos: Record<string, ComponentLogo> = {
  "apachereceiver": {
    "slug": "apache",
    "title": "Apache",
    "color": "#D22128"
  },
  "apachesparkreceiver": {
    "slug": "apachespark",
    "title": "Apache Spark",
    "color": "#E25A1C"
  },
  "awscloudwatchreceiver": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awscontainerinsightreceiver": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awsecscontainermetricsreceiver": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awsfirehosereceiver": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awslambdareceiver": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awss3receiver": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awsxrayreceiver": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "azureblobreceiver": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "azureeventhubreceiver": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "azurefunctionsreceiver": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "azuremonitorreceiver": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "ciscoosreceiver": {
    "slug": "cisco",
    "title": "Cisco",
    "color": "#1BA0D7"
  },
  "cloudflarereceiver": {
    "slug": "cloudflare",
    "title": "Cloudflare",
    "color": "#F38020"
  },
  "cloudfoundryreceiver": {
    "slug": "cloudfoundry",
    "title": "Cloud Foundry",
    "color": "#0C9ED5"
  },
  "couchdbreceiver": {
    "slug": "apachecouchdb",
    "title": "Apache CouchDB",
    "color": "#E42528"
  },
  "datadogreceiver": {
    "slug": "datadog",
    "title": "Datadog",
    "color": "#632CA6"
  },
  "dockerstatsreceiver": {
    "slug": "docker",
    "title": "Docker",
    "color": "#2496ED"
  },
  "elasticsearchreceiver": {
    "slug": "elasticsearch",
    "title": "Elasticsearch",
    "color": "#005571"
  },
  "envoyalsreceiver": {
    "slug": "envoyproxy",
    "title": "Envoy Proxy",
    "color": "#AC6199"
  },
  "faroreceiver": {
    "slug": "grafana",
    "title": "Grafana",
    "color": "#F46800"
  },
  "flinkmetricsreceiver": {
    "slug": "apacheflink",
    "title": "Apache Flink",
    "color": "#E6526F"
  },
  "fluentforwardreceiver": {
    "slug": "fluentd",
    "title": "Fluentd",
    "color": "#0E83C8"
  },
  "githubreceiver": {
    "slug": "github",
    "title": "GitHub",
    "color": "#181717"
  },
  "gitlabreceiver": {
    "slug": "gitlab",
    "title": "GitLab",
    "color": "#FC6D26"
  },
  "googlecloudmonitoringreceiver": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "googlecloudpubsubpushreceiver": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "googlecloudpubsubreceiver": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "googlecloudspannerreceiver": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "huaweicloudcesreceiver": {
    "slug": "huawei",
    "title": "Huawei",
    "color": "#FF0000"
  },
  "influxdbreceiver": {
    "slug": "influxdb",
    "title": "InfluxDB",
    "color": "#22ADF6"
  },
  "jaegerreceiver": {
    "slug": "jaeger",
    "title": "Jaeger",
    "color": "#66CFE3"
  },
  "journaldreceiver": {
    "slug": "linux",
    "title": "Linux",
    "color": "#FCC624"
  },
  "k8sclusterreceiver": {
    "slug": "kubernetes",
    "title": "Kubernetes",
    "color": "#326CE5"
  },
  "k8seventsreceiver": {
    "slug": "kubernetes",
    "title": "Kubernetes",
    "color": "#326CE5"
  },
  "k8sobjectsreceiver": {
    "slug": "kubernetes",
    "title": "Kubernetes",
    "color": "#326CE5"
  },
  "kafkametricsreceiver": {
    "slug": "apachekafka",
    "title": "Apache Kafka",
    "color": "#231F20"
  },
  "kafkareceiver": {
    "slug": "apachekafka",
    "title": "Apache Kafka",
    "color": "#231F20"
  },
  "kubeletstatsreceiver": {
    "slug": "kubernetes",
    "title": "Kubernetes",
    "color": "#326CE5"
  },
  "lokireceiver": {
    "slug": "grafana",
    "title": "Grafana",
    "color": "#F46800"
  },
  "macosunifiedloggingreceiver": {
    "slug": "apple",
    "title": "Apple",
    "color": "#000000"
  },
  "mongodbatlasreceiver": {
    "slug": "mongodb",
    "title": "MongoDB",
    "color": "#47A248"
  },
  "mongodbreceiver": {
    "slug": "mongodb",
    "title": "MongoDB",
    "color": "#47A248"
  },
  "mysqlreceiver": {
    "slug": "mysql",
    "title": "MySQL",
    "color": "#4479A1"
  },
  "nginxreceiver": {
    "slug": "nginx",
    "title": "NGINX",
    "color": "#009639"
  },
  "oracledbreceiver": {
    "slug": "cloud-oracle",
    "title": "Oracle Cloud",
    "color": "#F80000"
  },
  "otelarrowreceiver": {
    "slug": "apachearrow",
    "title": "Apache Arrow",
    "color": "#000000"
  },
  "otlpjsonfilereceiver": {
    "slug": "opentelemetry",
    "title": "OpenTelemetry",
    "color": "#000000"
  },
  "podmanreceiver": {
    "slug": "podman",
    "title": "Podman",
    "color": "#892CA0"
  },
  "postgresqlreceiver": {
    "slug": "postgresql",
    "title": "PostgreSQL",
    "color": "#4169E1"
  },
  "prometheusreceiver": {
    "slug": "prometheus",
    "title": "Prometheus",
    "color": "#E6522C"
  },
  "prometheusremotewritereceiver": {
    "slug": "prometheus",
    "title": "Prometheus",
    "color": "#E6522C"
  },
  "pulsarreceiver": {
    "slug": "apachepulsar",
    "title": "Apache Pulsar",
    "color": "#188FFF"
  },
  "rabbitmqreceiver": {
    "slug": "rabbitmq",
    "title": "RabbitMQ",
    "color": "#FF6600"
  },
  "redisreceiver": {
    "slug": "redis",
    "title": "Redis",
    "color": "#FF4438"
  },
  "simpleprometheusreceiver": {
    "slug": "prometheus",
    "title": "Prometheus",
    "color": "#E6522C"
  },
  "snowflakereceiver": {
    "slug": "snowflake",
    "title": "Snowflake",
    "color": "#29B5E8"
  },
  "splunkenterprisereceiver": {
    "slug": "splunk",
    "title": "Splunk",
    "color": "#000000"
  },
  "splunkhecreceiver": {
    "slug": "splunk",
    "title": "Splunk",
    "color": "#000000"
  },
  "vcenterreceiver": {
    "slug": "vmware",
    "title": "VMware",
    "color": "#607078"
  },
  "awsecsattributesprocessor": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "k8sattributesprocessor": {
    "slug": "kubernetes",
    "title": "Kubernetes",
    "color": "#326CE5"
  },
  "sumologicprocessor": {
    "slug": "sumologic",
    "title": "Sumo Logic",
    "color": "#000099"
  },
  "alibabacloudlogserviceexporter": {
    "slug": "alibabacloud",
    "title": "Alibaba Cloud",
    "color": "#FF6A00"
  },
  "awscloudwatchlogsexporter": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awsemfexporter": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awskinesisexporter": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awss3exporter": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "awsxrayexporter": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "azureblobexporter": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "azuredataexplorerexporter": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "azuremonitorexporter": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "cassandraexporter": {
    "slug": "apachecassandra",
    "title": "Apache Cassandra",
    "color": "#1287B1"
  },
  "clickhouseexporter": {
    "slug": "clickhouse",
    "title": "ClickHouse",
    "color": "#FFCC01"
  },
  "datadogexporter": {
    "slug": "datadog",
    "title": "Datadog",
    "color": "#632CA6"
  },
  "elasticsearchexporter": {
    "slug": "elasticsearch",
    "title": "Elasticsearch",
    "color": "#005571"
  },
  "faroexporter": {
    "slug": "grafana",
    "title": "Grafana",
    "color": "#F46800"
  },
  "googlecloudexporter": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "googlecloudpubsubexporter": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "googlecloudstorageexporter": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "googlemanagedprometheusexporter": {
    "slug": "googlecloud",
    "title": "Google Cloud",
    "color": "#4285F4"
  },
  "influxdbexporter": {
    "slug": "influxdb",
    "title": "InfluxDB",
    "color": "#22ADF6"
  },
  "kafkaexporter": {
    "slug": "apachekafka",
    "title": "Apache Kafka",
    "color": "#231F20"
  },
  "opensearchexporter": {
    "slug": "opensearch",
    "title": "OpenSearch",
    "color": "#005EB8"
  },
  "otelarrowexporter": {
    "slug": "apachearrow",
    "title": "Apache Arrow",
    "color": "#000000"
  },
  "prometheusexporter": {
    "slug": "prometheus",
    "title": "Prometheus",
    "color": "#E6522C"
  },
  "prometheusremotewriteexporter": {
    "slug": "prometheus",
    "title": "Prometheus",
    "color": "#E6522C"
  },
  "pulsarexporter": {
    "slug": "apachepulsar",
    "title": "Apache Pulsar",
    "color": "#188FFF"
  },
  "rabbitmqexporter": {
    "slug": "rabbitmq",
    "title": "RabbitMQ",
    "color": "#FF6600"
  },
  "sentryexporter": {
    "slug": "sentry",
    "title": "Sentry",
    "color": "#362D59"
  },
  "splunkhecexporter": {
    "slug": "splunk",
    "title": "Splunk",
    "color": "#000000"
  },
  "sumologicexporter": {
    "slug": "sumologic",
    "title": "Sumo Logic",
    "color": "#000099"
  },
  "awsproxy": {
    "slug": "cloud-aws",
    "title": "Amazon Web Services",
    "color": "#FF9900"
  },
  "azureauthextension": {
    "slug": "cloud-azure",
    "title": "Microsoft Azure",
    "color": "#0089D6"
  },
  "datadogextension": {
    "slug": "datadog",
    "title": "Datadog",
    "color": "#632CA6"
  },
  "jaegerremotesampling": {
    "slug": "jaeger",
    "title": "Jaeger",
    "color": "#66CFE3"
  },
  "k8sleaderelector": {
    "slug": "kubernetes",
    "title": "Kubernetes",
    "color": "#326CE5"
  },
  "sumologicextension": {
    "slug": "sumologic",
    "title": "Sumo Logic",
    "color": "#000099"
  },
  "datadogconnector": {
    "slug": "datadog",
    "title": "Datadog",
    "color": "#632CA6"
  },
  "grafanacloudconnector": {
    "slug": "grafana",
    "title": "Grafana",
    "color": "#F46800"
  },
  "otlpjsonconnector": {
    "slug": "opentelemetry",
    "title": "OpenTelemetry",
    "color": "#000000"
  }
};
